### ISSUE TITLE
Maven Central availability

### ISSUE THREAD

**Issue by pushbit** [wujingchao/SimpleTagImageView#3]
Has `simple-tag-imageview` been removed from Maven Central?  I'm no longer able to find it there.

**Comment by wujingchao** [comment]
You can configure your repository by this :https://bintray.com/repo/buildSettings?repoPath=%2Fbintray%2Fjcenter

I recommend use gradle or download release as a module!

**Comment by pushbit** [comment]
I'm already using Gradle and I downloaded 1.0.0 a few weeks ago, but for some reason my build wasn't able to download it earlier today.  But now I am able to download 1.0.1.  Though I still can't find the package on the JCenter website.  Maybe it hasn't been indexed yet or I'm not using the right search terms.
