### ISSUE TITLE
中文没有垂直居中英文是好的

### ISSUE THREAD

**Issue by MakoFeng** [wujingchao/SimpleTagImageView#5]
![qq 20160112114707](https://cloud.githubusercontent.com/assets/9279537/12254355/6d03798a-b922-11e5-90bc-d3cd9df6137c.png)
![qq 20160112115053](https://cloud.githubusercontent.com/assets/9279537/12254378/c16d108a-b922-11e5-84c1-4e7fc64103ef.png)

**Comment by wujingchao** [comment]
这个和字体有关系，你弄个按钮居中也是这种效果。
